name: Deploy NestJS App

on:
  push:
    branches:
      - development-vps

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install dependencies
        run: npm ci
          
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GCLIENTID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GCLIENT_SECRET }} \
            --build-arg FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} \
            --build-arg APPLE_PRIVATE_KEY=${{ secrets.APPLE_PRIV_KEY }} \
            --build-arg APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }} \
            --build-arg HOST_DB=${{ secrets.HOST_DB }} \
            --build-arg HOST_DB_PORT=${{ secrets.HOST_DB_PORT }} \
            --build-arg DB_UNAME=${{ secrets.HOST_DB_UNAME }} \
            --build-arg DB_UPASS=${{ secrets.HOST_DB_UPWD }} \
            --build-arg DB_NAME=${{ secrets.HOST_DB_NAME }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg GITHUB_CLIENT_ID=${{ secrets.GITHLIENT_ID }} \
            --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GITHCLIENT_SECRET }} -t thilak2302/app:latest . --push
          docker images  # List local images to verify the tag
          # docker push thilak2302/app:latest
          # docker pull thilak2302/app:latest
#            --env-file .env -t thilak2302/app:latest .

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker pull thilak2302/app:latest
            docker stop be_container || true
            docker rm be_container || true
            docker run --network=host -d --name be_container -p 2511:3001 \
              -e GITHUB_CLIENT_ID=${{ secrets.GITHLIENT_ID }} \
              -e GITHUB_CLIENT_SECRET=${{ secrets.GITHCLIENT_SECRET }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GCLIENTID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GCLIENT_SECRET }} \
              -e BACKEND_URL=${{ secrets.BACKEND_URL }} \
              -e APPLE_PRIVATE_KEY=${{ secrets.APPLE_PRIV_KEY }} \
              -e APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }} \
              -e HOST_DB=${{ secrets.HOST_DB }} \
              -e HOST_DB_PORT=${{ secrets.HOST_DB_PORT }} \
              -e DB_UNAME=${{ secrets.HOST_DB_UNAME }} \
              -e DB_UPASS=${{ secrets.HOST_DB_UPWD }} \
              -e DB_NAME=${{ secrets.HOST_DB_NAME }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              thilak2302/app:latest
